### ISSUE TITLE
Check that the (authentificated) user is enrolled in the course

### ISSUE THREAD

**Issue by Mogztter** [neo4j-contrib/training-v3#101]
Otherwise we should send him to the enrollment page.
We might need to configure this page if we cannot automatically guess the enrollment page from the current URL.

**Comment by ElaineRosenberg** [comment]
Current redirects that need to be configured for a module (not sure the best place to configure this?

4.0-intro-neo4j:  https://neo4j.com/graphacademy/online-training/introduction-to-neo4j-40/
