### ISSUE TITLE
Allow to define the author in the WordPress plugin

### ISSUE THREAD

**Issue by Mogztter** [neo4j-contrib/training-v3#107]
We will use the `author` attribute that contains the author’s full name.
It can be defined as part of the header:

```
= Title
Michael Hunger
```

Or as an attribute:

```
= Title
:author: Michael Hunger

== Section 1
```

**Comment by Mogztter** [comment]
Plugin moved to https://github.com/neo4j-contrib/wordpress-publish-gradle-plugin

**Comment by spgandhi** [comment]
@Mogztter Although its a little unlikely but would the plugin take care of a situation when there are multiple users with the same full name?

**Comment by Mogztter** [comment]
@spgandhi Yes we could use a specific attribute if the name is not unique (something like `:author-slug:` or `:author-id:`)
Currently, we rely on the REST API to find a user from a string.
I'm not entirely sure how it's working because the API can return result when no field seems to match. For instance, if you try:

```
http https://neo4j.com/wp-json/wp/v2/users\?search\="info"
```
(using [HTTPie](https://httpie.org/))

It will return a user named "Neo4j Staff Editor"... Also the email address is absent from the response :thinking: 

Anyway, could you please open an issue at: https://github.com/neo4j-contrib/wordpress-publish-gradle-plugin. I will try to implement a more robust mechanism when I have time.
