### ISSUE TITLE
Introduce a new command to generate an exercise PDF

### ISSUE THREAD

**Issue by Mogztter** [neo4j-contrib/training-v3#16]
Here's a summary:

Name | Intended users | Document type | File type | Generate | 
------------ | ------------- | ------------- | ------------- | -------------
Presentation | Trainers | reveal.js presentation | HTML | `./gradlew convertSlides`
Presentation support | Students | reveal.js presentation without speaker notes | PDF | manual
Online course | Students | HTML page | HTML | `./gradlew convertOnlineHtml`
course PDF | Students | Book document | PDF | `./gradlew convertOnlinePdf`
exercise PDF | Students | Article document | PDF | -

We should introduce a new command to generate exercise PDF: `./gradlew convertExercisePdf`.
The PDF will be generated in `build/exercise/*.pdf`.

Exercices should be written in separated AsciiDoc documents:

```
modules/4.0-neo4j-admin/docs/02_OverviewOfNeo4jAdministration.adoc
modules/4.0-neo4j-admin/docs/exercises/01_SettingUpNeo4jEnterpriseEditionEC2.adoc
```

The reason is that we want to convert only the exercises (not all the documents that might or might not contain an exercise).

The Gradle command will convert all the document in the `modules/4.0-neo4j-admin/docs/exercises/` folder.

**Comment by ElaineRosenberg** [comment]
This sounds like a good solution. Let's go for it.

**Comment by Mogztter** [comment]
In the end, `./gradlew convertOnlinePdf` also converts exercises PDF
