### ISSUE TITLE
Specific roles used in the slides produce conflicts

### ISSUE THREAD

**Issue by Mogztter** [neo4j-contrib/training-v3#22]
We are using a few specific roles in the slides that don't have any meaning in the PDF or HTML output. We also use generic term like "title".
The problem is that the stylesheet used in WordPress can match these roles.

We can resolve this issue using several techniques:
- Add a unique prefix "title" -> "slide-title"
- Use a more descriptive name "title" -> ?
- Use a conditional block 

```diff
+ifdef::backend-revealjs[[.title.gold]]
- [.title.gold]
== Exercise 1: Retrieving Nodes
```

The last solution is the only one that guarantees that they won't have any conflict (because the roles won't be in the output).

We could also use an extension to remove roles that begins with a given prefix. Please note that it can be costly if we need to check every nodes in the AST.

@ElaineRosenberg do you have any preference?

**Comment by ElaineRosenberg** [comment]
@Mogztter My preference would be to transition to a new prefix, slide-title as that is what it represents. I definitely don't want to introduce conditionals!

Thanks!

**Comment by Mogztter** [comment]
Fair enough. 
I've added a prefix in #26 but I think that the right way is to use a "functional" roles, for instance:

```adoc
[.summary]
== Summary

[.cyu]
== Check your understanding
```

But it might be too soon to introduce this change? Maybe once you've established a clear common structure we can introduce them?

**Comment by ElaineRosenberg** [comment]
Not sure what the [.summary] role would provide, unless it has something to do with persisting CYU results.  We definitely need the [.cyu] distinction for online.

**Comment by Mogztter** [comment]
It would replace the following definitions:

```adoc
[.slide-title.has-green-background.has-puzzle-background]
== Summary
```

```adoc
[.slide-section-title.has-purple-background.has-puzzle-background]
== Check your understanding
```

So instead of defining precisely the style of the slide, we just define an hint/role (ie. this is the summary section). Then we can use this hint/role to style the slide accordingly. Otherwise we are mixing presentation with content.
Since we are using a "functional" description it has less chance to create a conflict and we can decide if we want to apply a particular style when producing an online content (WordPress) or a slides deck.
Does it make sense?

**Comment by jexp** [comment]
I very much like having semantic roles !!
