### ISSUE TITLE
Wrong solution image for "Refactor example: Turn property values into labels for nodes"

### ISSUE THREAD

**Issue by futebolbryant** [neo4j-contrib/training-v3#266]
It seems this image is duplicated from the "Refactor example: Extracting nodes from properties" section.  The solution for the section "Refactor example: Turn property values into labels for nodes" is concerning projects and programming languages.

https://neo4j.com/graphacademy/training-gdm-40/05-refactoring-model/#_refactor_example_turn_property_values_into_labels_for_nodes

Sorry if this is not the right place for this type of feedback.  Loving the tutorial by the way.

**Comment by ElaineRosenberg** [comment]
This has been corrected. Thank you @futebolbryant !

Elaine
