### ISSUE TITLE
Unclear instructions in the Exercise 8.2: Modify the query to eliminate duplication (Instructions)

### ISSUE THREAD

**Issue by roger-yu-ds** [neo4j-contrib/training-v3#277]
In [Exercise 8.2: Modify the query to eliminate duplication (Instructions)](https://github.com/neo4j-contrib/training-v3/blob/ae30dd3538d584890c0bb53db168409f6caa6029/browser-guides/4.0-intro-neo4j-exercises/docs/08.adoc#exercise-82-modify-the-query-to-eliminate-duplication-instructions):
>The results returned from the previous query include multiple rows for a movie released value.

But actually there are no duplicates.

**Comment by ElaineRosenberg** [comment]
What is duplicated is the released value. That is, there are multiple rows for the same year.
