### ISSUE TITLE
Is the error expected in Exercise 12.7?

### ISSUE THREAD

**Issue by roger-yu-ds** [neo4j-contrib/training-v3#281]
In [Exercise 12.7: Use MERGE to create two nodes and a single relationship (Instructions)](https://github.com/neo4j-contrib/training-v3/blob/master/browser-guides/4.0-intro-neo4j-exercises/docs/12.adoc#exercise-127-use-merge-to-create-two-nodes-and-a-single-relationship-instructions), the instruction is to run the query
```
MERGE (p:Person {name: 'Robert Zemeckis'})-[:DIRECTED]->(m {title: 'Forrest Gump'})
```
which throws the `Neo.ClientError.Schema.ConstraintValidationFailed` error
```
Node(151) already exists with label `Person` and property `name` = 'Robert Zemeckis'
```
But there is no mention of the error in the explanation. I think it would be clearer for the learner if the error is mentioned, so that the learner wouldn't think that s/he has committed an error upstream.

**Comment by roger-yu-ds** [comment]
Actually the solution to the exercise, [Exercise 12.7: Use MERGE to create two nodes and a single relationship (Solution)](https://github.com/neo4j-contrib/training-v3/blob/master/browser-guides/4.0-intro-neo4j-exercises/docs/12.adoc#exercise-127-use-merge-to-create-two-nodes-and-a-single-relationship-solution) shows that the query should have executed properly.

![image](https://user-images.githubusercontent.com/7835508/124330660-3e9c2380-dbd1-11eb-9d29-748f09e2e342.png)

So something is definitely wrong.

**Comment by roger-yu-ds** [comment]
Actually, starting from Exercise 12.7, the format of the course changed to include the query in the Instruction step; the previous format doesn't show the query until the Solution step. Which makes me think the course hasn't been updated from this point onwards.

I've also noticed that subsequent queries don't quite correspond to the task at hand.

**Comment by ElaineRosenberg** [comment]
Hello @roger-yu-ds 

I just went through the exercises with the expected results. My guess is that you perhaps had already created a node with that label already?

If you reset your graph to the starting state, you should be able to go through the exercise without any errors.

Elaine
