### ISSUE TITLE
Exercise 13.1 has incorrect result in Sandbox

### ISSUE THREAD

**Issue by roger-yu-ds** [neo4j-contrib/training-v3#282]
In [Exercise 13.1: Add a uniqueness constraint to the graph (Solution)](https://github.com/neo4j-contrib/training-v3/blob/5a1c17a4d8886e7415aa31ba38d26b74924377e0/browser-guides/4.0-intro-neo4j-exercises/docs/13.adoc#exercise-131-add-a-uniqueness-constraint-to-the-graph-solution), running `CREATE CONSTRAINT PersonNameUniqueConstraint ON (p:Person) ASSERT p.name IS UNIQUE` is supposed to result in
![image](https://user-images.githubusercontent.com/7835508/124368687-b425f380-dca6-11eb-86c3-72cadc0a3b89.png)
But the actual result is `Constraint already exists: Constraint( id=2, name='constraint_e26b1a8b', type='UNIQUENESS', schema=(:Person {name}), ownedIndex=1 )`

**Comment by ElaineRosenberg** [comment]
You will get this error if the constraint already exists.  You can drop the constraint as follows:

DROP CONSTRAINT PersonNameUniqueConstraint
