### ISSUE TITLE
Exercise 17.5 needs extra set up

### ISSUE THREAD

**Issue by roger-yu-ds** [neo4j-contrib/training-v3#286]
[Exercise 17.5: Load the data with APOC (Instructions)](https://github.com/neo4j-contrib/training-v3/blob/ae30dd3538d584890c0bb53db168409f6caa6029/browser-guides/4.0-intro-neo4j-exercises/docs/17.adoc#exercise-175-load-the-data-with-apoc-instructions) requires adding the line `apoc.import.file.enabled=true` in the neo4j.conf file.

**Comment by ElaineRosenberg** [comment]
Good catch @roger-yu-ds 

I will update the instructions

Thank you
Elaine
