### ISSUE TITLE
`gds.alpha.degree.stream` not available

### ISSUE THREAD

**Issue by roger-yu-ds** [neo4j-contrib/training-v3#295]
[Part 2: Execute the Degree Centrality algorithm on a named graph (Instructions/Solution)](https://github.com/neo4j-contrib/training-v3/blob/ae30dd3538d584890c0bb53db168409f6caa6029/browser-guides/4.0-intro-graph-algos-exercises/docs/GraphCatalog.adoc#part-2-execute-the-degree-centrality-algorithm-on-a-named-graph-instructionssolution) instructs us to use `gds.alpha.degree.stream`, which results in

>There is no procedure with the name `gds.alpha.degree.stream` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.

Seems like this has been moved to production `gds.degree.stream`.

**Comment by ElaineRosenberg** [comment]
Duly noted and clarified in the browser guide.

Thanks @roger-yu-ds !
