### ISSUE TITLE
Incorrect link in the Label Propagation section

### ISSUE THREAD

**Issue by roger-yu-ds** [neo4j-contrib/training-v3#296]
In [Why use Label Propagation?](https://neo4j.com/graphacademy/training-iga-40/09-iga-40-community-detection/#_why_use_label_propagation):
>Finding potentially dangerous combinations of possible co-prescribed drugs, based on the chemical similarity and side effect profiles. This study is found [here](https://dl.acm.org/citation.cfm?id=2140465).

The link is to the Twitter paper, not the drugs one.

**Comment by ElaineRosenberg** [comment]
fixed the link.

Thanks @roger-yu-ds 

Elaine
