### ISSUE TITLE
02-best-practices40-using-indexes.adoc -- "tricky" question (or outdated)

### ISSUE THREAD

**Issue by karol-brejna-i** [neo4j-contrib/training-v3#312]
There is a quiz question:
"What makes creating a full-text schema index *different* from creating a property index?"

One of the good answers is:
"Full-text schema indexes can use relationship properties"

I believe it is wrong. You can have a "normal" index for properties of relationship, too:
https://neo4j.com/developer-blog/neo4j-4-3-blog-series-relationship-indexes/

**Comment by ElaineRosenberg** [comment]
Yes indeed. We have updated the course.

Thanks @karol-brejna-i !
