### ISSUE TITLE
"Nodes must have labels to categorize entities" - Introduction to Graph Data Modeling

### ISSUE THREAD

**Issue by karol-brejna-i** [neo4j-contrib/training-v3#313]
In https://github.com/neo4j-contrib/training-v3/edit/master/modules/graph-data-modeling/modules/ROOT/pages/01-introduction-graph-data-modeling.adoc you can read:

> Nodes and relationships are the key components of a graph. **Nodes must have labels to categorize entities**. Relationships must have direction and type. Nodes and relationships can have properties. A label is used to categorize a set of nodes. Properties are used to provide specific values to a node or relationship.

Labels are not mandatory, AFAIK. Maybe the sentence should sound  like "Nodes may have labels to categorize entities"?

**Comment by ElaineRosenberg** [comment]
Nodes need not have labels, but they would be pretty useless without them.
