### ISSUE TITLE
4.0 query tuning exercises 3.1 - wrong instructions for solution

### ISSUE THREAD

**Issue by AlexIsCoding** [neo4j-contrib/training-v3#317]
Hi folks, the instructions of the 3.1 exercise do not match the provided solution.
The instruction is using the parameter value UP and the solution is for the value Life

![image](https://user-images.githubusercontent.com/4171733/139538780-2999310c-17ab-4bd0-97af-e3b0d3232ee9.png)

![image](https://user-images.githubusercontent.com/4171733/139538798-9b8d1716-9dc1-48f1-924e-d7a1b4ef3f8e.png)

**Comment by ElaineRosenberg** [comment]
Thank you @AlexIsCoding for pointing this out. We have fixed the browser guide.
