### ISSUE TITLE
Honor toclevels in the "Contents" pane on the right of the page

### ISSUE THREAD

**Issue by Mogztter** [neo4j-contrib/training-v3#51]

**Comment by Mogztter** [comment]
@ElaineRosenberg The problem is that there's not enough vertical space to display the TOC:

![vertical-space](https://user-images.githubusercontent.com/333276/76398341-02f69e00-637d-11ea-9c36-6883cb113d2a.png)


The rest of the TOC will only be visible when we hit the bottom of the page:

![rest](https://user-images.githubusercontent.com/333276/76398455-35080000-637d-11ea-817c-3e0b7ecd4086.png)

**Comment by ElaineRosenberg** [comment]
I see what you mean. Let's just use the H2's. Maybe I will bump up some H3's to H2s to make the content more interesting.

Thanks!
Elaine

**Comment by Mogztter** [comment]
> I see what you mean. Let's just use the H2's.

Just to be sure, you mean first section level ? `== First section level` ? That's what we currently have right?

> Maybe I will bump up some H3's to H2s to make the content more interesting.

Ok.
If you agree, I will close this issue then.

**Comment by ElaineRosenberg** [comment]
All set - I will close it.

Thanks!
