### ISSUE TITLE
Allow to add or update the post tags in the WordPress plugin

### ISSUE THREAD

**Issue by Mogztter** [neo4j-contrib/training-v3#97]
The WordPress REST API is using the tags ids. In the AsciiDoc sources we don't want to use ids, so the plugin should resolve the tag id from a given slug/name using the following API: https://developer.wordpress.org/rest-api/reference/tags/#list-tags

If a tag is not found, we should warn the user and proceed?

**Comment by Mogztter** [comment]
Please note that it's also possible to automatically create (missing) tags but that could be harmful. For instance, if we make a typo, it will create a new tag with a typo.... :disappointed:

**Comment by jexp** [comment]
I would just create them or make it an option so in a rerun i can force creation

**Comment by Mogztter** [comment]
Plugin moved to https://github.com/neo4j-contrib/wordpress-publish-gradle-plugin

Tags are now supported but since (in our context) taxonomies are preferred over tags I will not do more work to force creation when a tag is missing.
