### ISSUE TITLE
Define a naming convention to map AsciiDoc attributes to WordPress fields

### ISSUE THREAD

**Issue by Mogztter** [neo4j-contrib/training-v3#98]
WordPress is using the following concepts:

- slug
- parent page
- author
- tags
- categories
- taxonomies
- meta

Currently we are using the following mapping:

WordPress field | AsciiDoc attribute
------------ | -------------
slug | :green_circle:  `:slug:`
parent page | :green_circle: `:parent-path: /labs`
author | :orange_circle: posts and pages are published with "restapi" as author
tags | :orange_circle: `:tags: foo,bar,baz` (not currently working)
categories |  :red_circle: not implemented
taxonomies |  :red_circle: not implemented
meta | :red_circle:  not implemented

### author

I guess we could use the built-in author of the AsciiDoc but we need to make sure that the author name matches a single user in WordPress. For instance:

```
/wp-json/wp/v2/users?search="Michael Hunger"
```
(It might be normal but I can't find myself in the `/users` API...?)

Or we might use an explicit attribute:

```
:author-slug: michael-hungerneotechnology-com
```

### categories

We use the same terminology for "categories" because the field is a list of values:

```
:categories: foo,bar,baz
```

### taxonomies

It's more complicated with "taxonomies" because we can define multiple taxonomies and a taxonomy has a name and a list of values.
Proposals:

**Using a prefix (and replacing `-` by `_`)**
```
:taxonomy-programming-language: java
:taxonomy-neo4j-version: 3-5
```

#### Using a list of key=value
```
:taxonomies: programming_language=java,neo4j_version=3-5
```

#### Using array syntax
```
:taxonomies1: programming_language=java
:taxonomies2: neo4j_version=3-5
```

#### Using hash syntax
```
:taxonomy-name1: programming_language
:taxonomy-value1: java
:taxonomy-name2: neo4j_version
:taxonomy-value2: 3-5
```

### meta

Do we use meta? I cannot find a pages or posts with meta so I'm not sure how they are structured.

**Comment by Mogztter** [comment]
Unless someone has a strong opinion against it, I will use the following syntax for taxonomies: 

```
:taxonomies: programming_language=java,neo4j_version=3-5
```

**Comment by jexp** [comment]
plus the others? tags/categories etc?

also as taxonomies?

**Comment by Mogztter** [comment]
> plus the others? tags/categories etc?
also as taxonomies?

For now, only taxonomies are supported but the logic is the same.
For tags and categories, I think we should use a list of values:

```
:tags: foo,bar,baz
:categories: foo,bar,baz
```

I believe that you want to create missing tags right? Should we use the same rule for categories?
For taxonomies, I simply ignore missing taxonomy.

Do you have an opinion for author? ie. should we use a specific attribute or the author of the document?

```adoc
= Title
Michael Hunger <michaelhunger@neo4j.org>
```

The author on ZendDesk and on WordPress will be the same? ie. the same email address will be used in both system?

**Comment by Mogztter** [comment]
Follow-up issues:

- Taxonomies #103 
- Author #107 
- Tags #108 
- Categories #109
